create table sensor(
                       id int GENERATED by default as identity PRIMARY KEY,
                       name varchar(100) UNIQUE
);

create table measurement(
                            id int GENERATED BY DEFAULT as identity PRIMARY KEY,
                            value float4 CHECK (value >= -100 and value <= 100),
                            is_raining boolean,
                            time timestamp,
                            sensor varchar(100) REFERENCES sensor(name) on delete cascade
);